spring:
   profiles:
    active:
    - dev
---
spring:
   profiles: dev
   application:
     name: microservicecloud-config-webank-dev
---
 spring:
    profiles: test
    application:
      name: microservicecloud-config-webank-test